http:
    host: 0.0.0.0
    port: 80

security:
    sessionSecret: testsecret123

strava:
    clientId: 123
    clientSecret: 123abc456def

messaging:
    connectionString: amqp://scott:dogfood@localhost:5672

